# Generated by Django 3.0.7 on 2021-03-26 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='normalize',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_sms', models.IntegerField()),
                ('nama_responden', models.CharField(max_length=50)),
                ('sms_spam', models.CharField(max_length=255)),
            ],
        ),
    ]
